package cn.edu.csu.dynamodb.example.demo.entity;

import cn.edu.csu.dynamodb.example.demo.entity.ids.UserId;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "dynamodb_demo")
@Data
public class User {

    @Id
    UserId userId;
    private String firstName;
    private String lastName;

    @DynamoDBIgnore
    public UserId getUserId() {
        return userId;
    }

    public User() {
        userId = new UserId();
    }

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "pk")
    public String getUsername() {
        return userId != null ? userId.getUsername() : null;
    }

    public void setUsername(String username) {
        if (userId != null) {
            userId.setUsername(username);
        }
    }

    @DynamoDBRangeKey(attributeName = "sk")
    public String getSk() {
        return userId != null ? userId.getSk() : null;
    }

    public void setSk(String sk) {
        if (userId != null) {
            userId.setSk(sk);
        }
    }

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "firstName-lastName-index", attributeName = "firstName")
    public String getFirstName() {
        return firstName;
    }
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "firstName-lastName-index", attributeName = "lastName")
    public String getLastName() {
        return lastName;
    }

    //setter & hashCode & equals
}
